language:
  - cpp
compiler:
  - gcc
before_install:
install:
  - sudo apt-get install qt4-default 
  - sudo apt-get install gdb 
before_script:
  - mkdir Build
  - cd Build
  - /usr/lib/x86_64-linux-gnu/qt4/bin/qmake ../devel/devel.pro -r -spec linux-g++-64 CONFIG+=debug
script:
  - make
  - make check
