addons:
  apt:
    packages:
    - qt4-default 
    - gcc-4.8
    - g++-4.8
language:
  - cpp
  - clang
compiler:
  - gcc
before_install:
install:
before_script:
  - mkdir Build
  - cd Build
  - /usr/lib/x86_64-linux-gnu/qt4/bin/qmake ../devel/devel.pro -r -spec linux-g++-64 CONFIG+=debug
script:
  - make
  - make check
