language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
  - sudo apt-get install qt4-default 
  - if test $CC = gcc; then sudo apt-get install --yes --force-yes gcc-4.8 g++-4.8; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
before_script:
  - mkdir Build
  - cd Build
  - /usr/lib/x86_64-linux-gnu/qt4/bin/qmake ../devel/devel.pro -r -spec linux-g++-64 CONFIG+=debug
script:
  - make
- ./devel